In [1]:
import numpy as np

In [2]:
zeros = np.zeros(10)
ones = np.ones(10)
zeros, ones

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [3]:
zeros = np.zeros((5, 4))

In [4]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
linspace = np.linspace(10, 50, 100)
linspace

array([10.        , 10.4040404 , 10.80808081, 11.21212121, 11.61616162,
       12.02020202, 12.42424242, 12.82828283, 13.23232323, 13.63636364,
       14.04040404, 14.44444444, 14.84848485, 15.25252525, 15.65656566,
       16.06060606, 16.46464646, 16.86868687, 17.27272727, 17.67676768,
       18.08080808, 18.48484848, 18.88888889, 19.29292929, 19.6969697 ,
       20.1010101 , 20.50505051, 20.90909091, 21.31313131, 21.71717172,
       22.12121212, 22.52525253, 22.92929293, 23.33333333, 23.73737374,
       24.14141414, 24.54545455, 24.94949495, 25.35353535, 25.75757576,
       26.16161616, 26.56565657, 26.96969697, 27.37373737, 27.77777778,
       28.18181818, 28.58585859, 28.98989899, 29.39393939, 29.7979798 ,
       30.2020202 , 30.60606061, 31.01010101, 31.41414141, 31.81818182,
       32.22222222, 32.62626263, 33.03030303, 33.43434343, 33.83838384,
       34.24242424, 34.64646465, 35.05050505, 35.45454545, 35.85858586,
       36.26262626, 36.66666667, 37.07070707, 37.47474747, 37.87

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.random.rand(10)

array([0.85710896, 0.22341211, 0.77592396, 0.94986279, 0.45270243,
       0.31114099, 0.26455663, 0.98319368, 0.91814418, 0.94557949])

In [8]:
np.random.rand(5, 5)

array([[0.39447892, 0.54308332, 0.61272379, 0.79745188, 0.80365372],
       [0.09903751, 0.56308241, 0.38095281, 0.11360725, 0.42688737],
       [0.54284485, 0.35843112, 0.73151735, 0.22654854, 0.40621897],
       [0.43108638, 0.75010974, 0.42453148, 0.30471343, 0.59600789],
       [0.18458139, 0.38436574, 0.91493548, 0.04087459, 0.41468957]])

In [16]:
a = np.random.randint(1, 10, (10, 10)) # 1, 10 => range random elements. (10, 10) matrix shape
a

array([[2, 3, 7, 5, 7, 7, 5, 2, 8, 5],
       [6, 6, 2, 6, 5, 6, 2, 7, 6, 6],
       [1, 2, 1, 5, 1, 9, 5, 2, 2, 9],
       [4, 3, 7, 1, 2, 2, 2, 4, 5, 7],
       [6, 8, 2, 3, 8, 4, 1, 7, 8, 3],
       [3, 6, 5, 2, 5, 4, 8, 4, 7, 2],
       [5, 3, 4, 6, 2, 8, 7, 7, 9, 7],
       [4, 6, 9, 3, 8, 7, 8, 1, 7, 7],
       [9, 1, 2, 7, 4, 1, 2, 8, 5, 2],
       [3, 7, 6, 4, 8, 4, 2, 4, 4, 9]])

In [17]:
q1 = [1, 2, 3, 4, 5, 6, 7]
q2 = q1 # get reference
q2[3] = 10

In [18]:
q1

[1, 2, 3, 10, 5, 6, 7]

In [19]:
q1 = [1, 2, 3, 4, 5, 6, 7]
q2 = q1.copy() # get copy
q2[3] = 10
q1

[1, 2, 3, 4, 5, 6, 7]

In [20]:
q1 = np.array([1, 2, 3, 4, 5, 6, 7]) # numpy array take reference of  array every time.
q2 = q1[2:5]
q2

array([3, 4, 5])

In [21]:
q2[2] = 10

In [22]:
q1

array([ 1,  2,  3,  4, 10,  6,  7])

In [23]:
q1 = np.random.rand(5, 4)

In [24]:
q1

array([[0.01734998, 0.91929656, 0.28615238, 0.38404369],
       [0.74617843, 0.17005664, 0.83913539, 0.13564035],
       [0.26657978, 0.45976534, 0.11193864, 0.82508704],
       [0.64579715, 0.95737764, 0.80634433, 0.09520263],
       [0.13969082, 0.36312788, 0.2987247 , 0.82868339]])

In [25]:
q2 = q1.reshape(4, 5)
q2

array([[0.01734998, 0.91929656, 0.28615238, 0.38404369, 0.74617843],
       [0.17005664, 0.83913539, 0.13564035, 0.26657978, 0.45976534],
       [0.11193864, 0.82508704, 0.64579715, 0.95737764, 0.80634433],
       [0.09520263, 0.13969082, 0.36312788, 0.2987247 , 0.82868339]])

In [26]:
q3 = q1.reshape(3, 3)

ValueError: cannot reshape array of size 20 into shape (3,3)

In [27]:
q3 = q1.reshape(2, 10)
q3

array([[0.01734998, 0.91929656, 0.28615238, 0.38404369, 0.74617843,
        0.17005664, 0.83913539, 0.13564035, 0.26657978, 0.45976534],
       [0.11193864, 0.82508704, 0.64579715, 0.95737764, 0.80634433,
        0.09520263, 0.13969082, 0.36312788, 0.2987247 , 0.82868339]])

In [28]:
q4 = q1.reshape(20)
q4

array([0.01734998, 0.91929656, 0.28615238, 0.38404369, 0.74617843,
       0.17005664, 0.83913539, 0.13564035, 0.26657978, 0.45976534,
       0.11193864, 0.82508704, 0.64579715, 0.95737764, 0.80634433,
       0.09520263, 0.13969082, 0.36312788, 0.2987247 , 0.82868339])

In [29]:
q1.reshape(20, 1)

array([[0.01734998],
       [0.91929656],
       [0.28615238],
       [0.38404369],
       [0.74617843],
       [0.17005664],
       [0.83913539],
       [0.13564035],
       [0.26657978],
       [0.45976534],
       [0.11193864],
       [0.82508704],
       [0.64579715],
       [0.95737764],
       [0.80634433],
       [0.09520263],
       [0.13969082],
       [0.36312788],
       [0.2987247 ],
       [0.82868339]])

In [30]:
q5 = q1[:2, :2].reshape(2, 2) # make matrix 2 x 2
q5

array([[0.01734998, 0.91929656],
       [0.74617843, 0.17005664]])

In [32]:
r = np.random.randint(1, 10, (5, 5))

In [33]:
r

array([[7, 6, 3, 3, 7],
       [8, 8, 6, 7, 2],
       [7, 6, 2, 6, 2],
       [5, 2, 5, 4, 3],
       [5, 9, 8, 2, 4]])

In [34]:
r[:,:3] # 3 columns

array([[7, 6, 3],
       [8, 8, 6],
       [7, 6, 2],
       [5, 2, 5],
       [5, 9, 8]])

In [35]:
r[2:4, :3] += 1
r

array([[7, 6, 3, 3, 7],
       [8, 8, 6, 7, 2],
       [8, 7, 3, 6, 2],
       [6, 3, 6, 4, 3],
       [5, 9, 8, 2, 4]])

In [36]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
np.setdiff1d(a, b)

array([1, 2, 3])

In [37]:
np.random.randn(10)

array([ 0.11542525, -1.09397845, -1.37919275, -0.00394791,  1.00480482,
        1.54731119,  0.6811939 , -1.27814239, -0.41484933,  1.01266284])