# Yessenov DATA LAB
### Week 1: Intro to Python

In [1]:
a = {1, 2, 3, 4, 5}
print(all(value > 0 for value in a))

True


#### input, output

In [1]:
print(1 + 1) # + sum
print(2 - 2) # - subtract
print(3 * 3) # * mutiply
print(5 / 2) # / floating division
print(6 // 4) # // integer division
a = 5
a = "Hello, Yessenov!"
print(a) # variable changing

2
0
9
2.5
1
Hello, Yessenov!


#### Data types, data structures

In [3]:
int_value = 5 # int
float_value = 5.4 # float
string_value = "abc" # str ~ string
bool_value = True # bool
list_data = [1, 2, 3, 5, 6] # list
tuple_value = (1, 2, 3) # tuple
set_data = {2, 3, 4, 5} # set
dict_data = {"Eldan":"Abdrashim", "Daniyar":"Mukhtarhanuly"} # dict ~ dictionary

print("integer", int_value)
print("float", float_value)
print("string", string_value)
print("bool", bool_value)
print("list", list_data)
print("tuple", tuple_value)
print("set", set_data)
print("dictionary", dict_data)

integer 5
float 5.4
string abc
bool True
list [1, 2, 3, 5, 6]
tuple (1, 2, 3)
set {2, 3, 4, 5}
dictionary {'Eldan': 'Abdrashim', 'Daniyar': 'Mukhtarhanuly'}


#### Loops 

In [4]:
array = [1, 1, 2, 3, 5, 8, 13]
array.append(21)
print(array) # print all data
print(array[0]) # print first element; array[0] = 1. Array begin from zero
print(array[2]) # print thrid element; array[2] = 2. 
print(array[-1]) # print last element; array[-1] = 21.
print(array[:5]) # print first five elements; array[:5] = 1, 1, 2, 3, 5
print(array[-3:]) # print last three elements; array[-3] = 5, 8, 13
print(array[3:5]) # print elements between 3 and 5; array[3:5] = 3, 5; array[3:5] ~ [3, 5) пятый элемент массива, не включается.

[1, 1, 2, 3, 5, 8, 13, 21]
1
2
21
[1, 1, 2, 3, 5]
[8, 13, 21]
[3, 5]


In [5]:
for element in array:
    print(element * 2) # print each element of array multiply by 2

2
2
4
6
10
16
26
42


In [7]:
for element in array[:3]:
    print(element) # print first three elements
print("First three elements")

1
1
2
First three elements


In [8]:
print("{} First three elements".format(array[:3]))

[1, 1, 2] First three elements


In [9]:
print("Last three elements {}".format(array[-3:]))

Last three elements [8, 13, 21]


In [10]:
for index in range(5, 20, 2):
    print(index) # print values from 5 to exclusive 20 with 2 steps. Which is means 5, 7, 9 and so on.

5
7
9
11
13
15
17
19


In [12]:
for value in range(0, 10): # range exclusive
    if value > 5 and value < 10: # if it's condition to checkout something, it that example value more than 5 and less than 10
        print(value) # print values which is more than five

6
7
8
9


In [13]:
countOfEvens = 0
for element in array:
    if element % 2 == 0:
        countOfEvens += 1
        
print(countOfEvens) # print count of evens in array

2


## Conclusion
### Intro to python

In [15]:
sorted(array, reverse=True)

[21, 13, 8, 5, 3, 2, 1, 1]

In [16]:
sorted(array)

[1, 1, 2, 3, 5, 8, 13, 21]

## Library numpy

In [17]:
import numpy as np # add library numpy in short-cast np

In [18]:
matrix = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [0, 2, 4, 6, 9]
] 
print(matrix[0][4]) # print first row and 5th element = 5
print(matrix[1][2]) # print second row and 3th element = 8

5
8


In [20]:
np_a = np.array([1, 2, 3, 4, 5])
np_b = np.array([1, 0, 0, 1, 1])
print(np_a - np_b) # print list where every element a minus b. 

[0 2 3 3 4]


In [21]:
np_a = np.array([0, 1, 2, 5, 6, 9, 10, 13, 15, 18, 6, 12])
np_a

array([ 0,  1,  2,  5,  6,  9, 10, 13, 15, 18,  6, 12])

### Function reshape

In [22]:
np_a = np_a.reshape(3, 4)
np_a

array([[ 0,  1,  2,  5],
       [ 6,  9, 10, 13],
       [15, 18,  6, 12]])

In [24]:
np_a = np_a.reshape(4, 3)
np_a

array([[ 0,  1,  2],
       [ 5,  6,  9],
       [10, 13, 15],
       [18,  6, 12]])

In [28]:
np_a = np.array([[1, 2, 3], [3, 2, 1], [4, 4, 4]])
np_b = np_a
np_a[0, 0] = 0
print(np_b)

[[0 2 3]
 [3 2 1]
 [4 4 4]]


### Additional functionality numpy

In [30]:
np_a[np_a < 3] # Output every element less than some x, in this example x = 3

array([0, 2, 2, 1])

In [31]:
np_a.mean() # mean in statistic(mu), mean = sum(np_a) / len(np_a)

2.5555555555555554

In [32]:
np_a.std() # standard deviation in statistic(sigma), sigma = sqrt(sum(x_i - mean) / len(np_a))

1.3425606637327303

In [38]:
np_a.T # or np.transpose(np_a). Transpose matrix, switch row to colum

array([[0, 3, 4],
       [2, 2, 4],
       [3, 1, 4]])

In [39]:
np_a.cumsum() # New list of elements with cumulative sum

array([ 0,  2,  5,  8, 10, 11, 15, 19, 23])

## Library pandas

In [40]:
import pandas as pd # add library with short-cast name pd

In [43]:
data = {"Animal": ["Peregrine falcon", "Golden eagle", "Cheetah", "Sailfish", "Swordfish"],
       "MaxSpeed": [389, 320, 109, 109, 97],
       "Class": ["Flight", "Flight", "Land", "Swimming", "Swimming"]
       }
df = pd.DataFrame(data,
                 columns = ["Animal", "MaxSpeed", "Class"])
df

Animal  MaxSpeed     Class
0  Peregrine falcon       389    Flight
1      Golden eagle       320    Flight
2           Cheetah       109      Land
3          Sailfish       109  Swimming
4         Swordfish        97  Swimming

In [44]:
df[df["MaxSpeed"] > 100]

Animal  MaxSpeed     Class
0  Peregrine falcon       389    Flight
1      Golden eagle       320    Flight
2           Cheetah       109      Land
3          Sailfish       109  Swimming

In [46]:
df = df.drop("Class", axis = 1) # Erase all column of df
df

Animal  MaxSpeed
0  Peregrine falcon       389
1      Golden eagle       320
2           Cheetah       109
3          Sailfish       109
4         Swordfish        97

In [47]:
df = df.sort_values(by = "MaxSpeed") # sorting row by MaxSpeed, in ascending order
df

Animal  MaxSpeed
4         Swordfish        97
2           Cheetah       109
3          Sailfish       109
1      Golden eagle       320
0  Peregrine falcon       389

### Additional functionality pandas

In [48]:
df.iloc[[0],[0]] # Get element 

Animal
4  Swordfish

In [49]:
df.loc[[0], ["MaxSpeed"]] # Get first row value of "MaxSpeed"

MaxSpeed
0       389

In [50]:
df.ix[2] # Get third row

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Animal      Cheetah
MaxSpeed        109
Name: 2, dtype: object

In [51]:
df.loc[[2]] # Get third row

Animal  MaxSpeed
2  Cheetah       109

In [52]:
df.ix[:] # Get all rows

Animal  MaxSpeed
4         Swordfish        97
2           Cheetah       109
3          Sailfish       109
1      Golden eagle       320
0  Peregrine falcon       389

In [53]:
df.ix[:, "MaxSpeed"] # Get each "MaxSpeed" columns

4     97
2    109
3    109
1    320
0    389
Name: MaxSpeed, dtype: int64

In [54]:
df.info() # information 

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 4 to 0
Data columns (total 2 columns):
Animal      5 non-null object
MaxSpeed    5 non-null int64
dtypes: int64(1), object(1)
memory usage: 280.0+ bytes


In [56]:
df.columns # Show each columns with dtype

Index(['Animal', 'MaxSpeed'], dtype='object')

In [57]:
df.head() # Show first five elements by default(5)

Animal  MaxSpeed
4         Swordfish        97
2           Cheetah       109
3          Sailfish       109
1      Golden eagle       320
0  Peregrine falcon       389

In [58]:
df.count() # Count of rows without NaN values

Animal      5
MaxSpeed    5
dtype: int64

## Work with file

In [62]:
import pandas as pd
import os
os.getcwd()  # command to check current directory

'/Users/Eldan/Desktop/Data Science/Yessenov/Data Lab/Week1_Python'

In [66]:
file = pd.read_csv("out.csv") # read csv file
print(type(file))
file.head()

<class 'pandas.core.frame.DataFrame'>


Unnamed: 0             0
0           0  1.437714e+06
1           1  3.639111e+06
2           2  4.317179e+06
3           3  1.634269e+07
4           4  2.775314e+06